### ISSUE TITLE
How do I disable anti-aliasing?

### ISSUE THREAD

**Issue by Goy288** [krzys-h/UndertaleModTool#41] opened 2018-11-04 15:40 UTC
I imported a sprite sheet and upon seeing it in game it was all blurry due to anti-aliasing. How do I disable this?

**Comment by krzys-h** [comment] 2018-11-04 19:43
Can you show a screenshot of what you mean? I've never seen that happen.

**Comment by Goy288** [comment] 2018-11-05 00:58
![image](https://user-images.githubusercontent.com/44177200/47972623-c8774580-e052-11e8-97a9-8f7e81d30a76.png)
Here you go.

**Comment by krzys-h** [comment] 2018-11-05 14:18
It does look weird indeed... are you sure you didn't accidentaly resize the texture? Try exporting the existing texture and editing that to make sure the parameters are correct.

**Comment by krzys-h** [comment] 2018-11-15 17:30
Did you ever figure out what causes this?

**Comment by Goy288** [comment] 2018-11-15 19:29
sorry whoops

**Comment by Grossley** [comment] 2019-07-15 00:54
> Unfortunately, no. I exported the textures like you recommended, and they do not come out as blurry. I checked both the bounding size of the texture and the size of the sprite and they both seem to be identical. Perhaps there is a default texture setting that makes textures and sprite sheets automatically activate anti-aliasing?

Hi. Have you tried ensuring that the dimensions of the texture sheet is a multiple of a power of 2? Example: 1024 by 1024, 512 by 1024, 256 by 512, and so on and so forth. I have found that if the dimensions are not a power of two that it can produce this anti-aliasing.

**Comment by Kneesnap** [comment] 2019-07-16 19:44
Do you mind posting the sprite you are importing, so I can test?

**Comment by Goy288** [comment] 2019-07-17 17:30
> Do you mind posting the sprite you are importing, so I can test?

Here are the [sprites](https://www.deviantart.com/elazulmax/art/Frisk-The-Frisk-613490538), made by [elazulmax](https://www.deviantart.com/elazulmax) on [Deviantart](https://www.deviantart.com).
I did modify the sprites a bit to fit the game a little better, but if you want it, I'll need to get it off my dusty old laptop first.

> Hi. Have you tried ensuring that the dimensions of the texture sheet is a multiple of a power of 2? Example: 1024 by 1024, 512 by 1024, 256 by 512, and so on and so forth. I have found that if the dimensions are not a power of two that it can produce this anti-aliasing.

Well the sprite sheet I used just had different proportions and not a direct upscaling, so I'm not sure if that exactly applies here.

**Comment by Kneesnap** [comment] 2019-07-17 22:15
So, the good news is I can reproduce the blurriness.

The bad news is that this is unfortunately not something that can be changed for now, until we have a texture manager system which can generate texture pages.

The blurriness comes from that you can't add a sprite to a texture page which is larger than the original without it getting scaled down, because it just wouldn't fit, it would overwrite the graphics of other sprites.

I know you mentioned that you could export it without issue, however I don't think that's what it seemed. I think UTMT upscaled what you exported back to the original resolution, but didn't actually give you the original image. It may have even been higher quality than what you saw in-game, however UTMT uses high-quality scaling while the GMS runner might not.

I do not believe this is anti-aliasing or interpolation because that would be applied to the entire game,  there isn't a way to specify this on a per texture page item basis.

However, the good news is, we do plan to add a texture page manager eventually, so instead of having to work with existing sprite boundaries we'll just be able to have it automatically manage texture pages.
If you do not want to wait until then, you could actually still import this texture at full resolution, if you found an area which didn't have any overlapping sprites.

**Comment by Kneesnap** [comment] 2019-07-17 22:24
I just did it to show the difference.

Importing at full resolution without any resizing or overlap.
![image](https://user-images.githubusercontent.com/6562913/61415854-bb2f7d80-a8a6-11e9-92d6-af8b83e309ca.png)

Importing at scaled resolution. (Slightly worse quality because I recorded to get the right animation frame, but it is still very clearly blurry.)
![image](https://user-images.githubusercontent.com/6562913/61415907-f631b100-a8a6-11e9-8aa6-dab8b54075e8.png)

**Comment by Kneesnap** [comment] 2019-07-18 01:21
I will close this once I get confirmation from @Goy288

**Comment by Goy288** [comment] 2019-07-19 01:41
Admittedly, I don't know how to do what you just described, so I'll just wait until the texture manager comes out so I can fix the sprites.
Here's the full modified version of the sheet btw:
![image](https://user-images.githubusercontent.com/44177200/61503177-a5e04f00-a98b-11e9-9f57-55f61ea8f980.png)

**Comment by Kneesnap** [comment] 2019-07-19 01:44
Alrighty.

**Closed by Kneesnap** 2019-07-19 01:44 UTC
Labels: question
