### ISSUE TITLE
Unknown Chunk PSEM Error

### ISSUE THREAD

**Issue by Recruit75** [krzys-h/UndertaleModTool#1231] opened 2023-03-24 09:00 UTC
### Describe the bug

When opening the data.win for [Nova Drift](https://store.steampowered.com/app/858210/Nova_Drift/) experimental branch, this error shows up:

<img width="218" alt="error3" src="https://user-images.githubusercontent.com/128734917/227472036-340fe4c3-abba-4e06-8579-4e968bf04ae5.png">

Nova Drift's experimental branch is using Gamemaker 2023.2.1

### Reproducing steps

1. Open UndertaleModTool
2. Open data.win inside the tool
3. Error Pop-up box appears
4. File is not loaded at all, modding cannot be achieved as a result.

### Setup Details

1. Using UndertaleModTool v:5.1.0 Release SingleFile=False\
2. Windows 10
3. Game: [Nova Drift](https://store.steampowered.com/app/858210/Nova_Drift/), experimental branch.

**Comment by Jacky720** [comment] 2023-03-24 17:17
Duplicate of #1209.

**Closed** 2023-03-25 13:28 UTC
Labels: bug
