### ISSUE TITLE
The text editor doesn't open your script where you left it

### ISSUE THREAD

**Issue by Shweetz** [krzys-h/UndertaleModTool#1142] opened 2022-12-21 19:15 UTC
### Describe the bug

If you open a code decompiler, leave it, scroll something else, come back, it's not where you left it.
The line should be remembered for every open tab + undo/redo history

### Reproducing steps

Open for example a code decompiled and scroll to the bottom of the text editor
Go to a different tab with another code decompiled or use the arrow to go to the previous code decompiled
The text editor is not where you left it last time, it is now at the bottom 

### Setup Details

1. GUI-windows-latest-isBundled-true-isSingleFile-true (bleeding edge as of 09/12/2202)
2. Windows 10

**Comment by VladiStep** [comment] 2022-12-21 20:09
This is a duplicate of #1020

**Comment by Grossley** [comment] 2022-12-21 23:31
Duplicate, closing.

**Closed** 2022-12-21 23:31 UTC
Labels: bug
