### ISSUE TITLE
If you go into an editing menu, make it editable, and then go load another data.win it throws an error window.

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#175] opened 2019-05-21 21:18 UTC
If you go into an editing menu and make it editable and then go load another data.win it throws an error message.

**Comment by Kneesnap** [comment] 2019-05-21 21:42
Can you give an example of what window + what game? I can't seem to reproduce this.

**Comment by Grossley** [comment] 2019-05-21 21:50
Undertale v1.08. Open "gml_Script_attention_hackerz_no_2", make it editable (the text will be black, this occurs both in Disassembly and Decompiled windows), and then load a data.win while the text is black (i.e. changes unapplied). When it loads it should throw up an error window after it is completed loading.

**Comment by Kneesnap** [comment] 2019-05-21 21:51
Gotcha, can reproduce.

**Comment by Kneesnap** [comment] 2019-05-21 21:53
An assertation occurs that makes sure this.DataContext is UndertaleCode and not null, however this focus change is caused by loading a new data.win, not by switching away. Maybe we should change this assertation into an if statement that will return if the condition fails.

**Comment by Kneesnap** [comment] 2019-05-22 02:27
Fixed in https://github.com/Kneesnap/UndertaleModTool/commit/1180192979271a1fdbfbb44aaed96a4357fb7581

**Closed** 2019-05-22 02:31 UTC
