### ISSUE TITLE
Adding a string or variable in UndertaleModTool consistently causes crash

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#170] opened 2019-05-15 00:08 UTC
Adding a string or variable in UndertaleModTool consistently causes the program to crash and immediately close. It doesn't matter if this is a new game or not. It just doesn't work.

**Comment by colinator27** [comment] 2019-05-15 00:25
Can't reproduce on my computer, likely a compatibility issue or something like that.

**Comment by colinator27** [comment] 2019-05-15 02:24
Added a fix locally, will make PR soon/eventually with other crash fixes

**Comment by Kneesnap** [comment] 2019-05-20 04:44
Fixed in https://github.com/Kneesnap/UndertaleModTool/commit/c73134618e80705399ee938333fc076cff0e6a24

**Closed** 2019-05-22 19:24 UTC
Labels: bug, editors
