### ISSUE TITLE
The Bug about  Extract Texture in Rabbit Knight: Reading Chunk OJBT

### ISSUE THREAD

**Issue by him7778** [krzys-h/UndertaleModTool#984] opened 2022-06-16 13:48 UTC
### Describe the bug

When I want to extract the files of this game, I stay at this interface and can only use the task manager to exit.

How can I change this situation?(The game was released on June 12)

### Reproducing steps

![Snipaste_2022-06-16_19-14-06](https://user-images.githubusercontent.com/107375217/174084047-942f6886-5409-47d7-98b6-c0a61274eff1.png)

### Setup Details

Undertalemodtool v:3c421d1(master)

**Comment by Miepee** [comment] 2022-06-16 13:50
Link to game: https://m36games.itch.io/rabbit-knight

**Comment by him7778** [comment] 2022-06-16 13:53
> 游戏链接：[https ://m36games.itch.io/rabbit-knight](https://m36games.itch.io/rabbit-knight)

I downloaded it from that website, but it looks like this when I open it with the latest version of UndertaleModTool, and It can't load the material.

**Comment by Miepee** [comment] 2022-06-16 14:07
Can you please re-add the game name to the issue title (and issue description)?

**Comment by Miepee** [comment] 2022-06-20 10:12
Now that the aforementioned PR is closed, this is a duplicate of #945

**Closed** 2022-06-20 15:02 UTC
Labels: bug
