### ISSUE TITLE
Load error while reading chunk

### ISSUE THREAD

**Issue by ErikSpyro** [krzys-h/UndertaleModTool#1547] opened 2023-11-20 09:03 UTC
### Describe the bug

When trying to load the data file, the mod tool spits out an error. It worked fine before GameMaker updated to the latest version. I don't know if Steam Cloud could effect anything since the game did update to add that, but also had to update GameMaker in order to release it.
![Namnlös](https://github.com/krzys-h/UndertaleModTool/assets/151511909/84a7e341-a60c-4ff4-994d-4b58e6011afc)

It did say something about invalid ID or something before this problem when loaded of the first time, but it never effected anything from what I could tell. And after the first load, it wouldn't complain anymore about it.
![Namnlös](https://github.com/krzys-h/UndertaleModTool/assets/151511909/c8dfa88d-107c-446e-89b4-3cfc25b7225e)

If there is anything more I need to provide, just tell me.

### Reproducing steps

1. Open UndertaleModTool
2. Load the game
3. Error shows up

### Setup Details

UndertaleModTool 0.5.1.0 (Bleeding Edge)
Windows 10 Home (version 19045.3693)
Game: The Bunny Graveyard (Steam version)

**Comment by Jacky720** [comment] 2023-11-20 13:21
Do you know the approximate GameMaker version of the game, or at least the most recent release date?

**Comment by ErikSpyro** [comment] 2023-11-20 15:10
The update for the game was released on the 6th November 2023, so it must be GameMaker 2023.8.2.108 - released the 10th October 2023.

**Comment by AndrewDemidov** [comment] 2023-12-18 19:34
Popping in due to the same error message.
After my downloading **UMT v0.5.1.0 (the stable release)** and trying it on **"Undertale Yellow" v1.1** ( https://gamejolt.com/games/UndertaleYellow/136925 ) UMT also encounters an **"invalid boolean" in the PSEM chunk** (as follows), and then just **doesn't open the file** at all (so I can't even say, what the game's engine's version is!):

`---------------------------
Load error
---------------------------
An error occured while trying to load:
Invalid boolean value: 4281479935
at 01126FA0 while reading object UndertaleModLib.Models.UndertaleParticleSystemEmitter
while reading item 1 of 3 in a list of UndertaleModLib.Models.UndertaleParticleSystemEmitter in chunk PSEM
---------------------------
ОК   
---------------------------
`

The game itself so far is played without errors or failures.

As can be seen, it's a different invalid value at a different offset, and the list's length is also different, but it clearly has to do with the chunk.

**Comment by Jacky720** [comment] 2023-12-18 19:41
Please update to the latest Bleeding Edge release of the mod tool.

**Comment by AndrewDemidov** [comment] 2023-12-19 23:00
> Please update to the latest Bleeding Edge release of the mod tool.

Thank you. The fixes for the PSEM chunk seem to be working in "Bleeding edge"! I can confirm, that not only does UMT open the file successfully, but it seems to display info on particle systems and emitters as well!

Does it mean the bug is resolved now? Does it need more testing?

**Comment by Jacky720** [comment] 2023-12-19 23:08
If other bugs crop up related to the version detection, they deserve their own issues. Please close this one.

**Comment by AndrewDemidov** [comment] 2023-12-19 23:30
Darn it, help, how do I close this one?!..

**Comment by Jacky720** [comment] 2023-12-20 00:17
There should be a "Close Issue" button next to the "Comment" button.

**Comment by AndrewDemidov** [comment] 2023-12-20 00:49
> There should be a "Close Issue" button next to the "Comment" button.

Hm... I see none... Can *you* close it? Or can only a higher-up do so?..

**Comment by Jacky720** [comment] 2023-12-20 00:54
Oh, you didn't open it, silly me. It has to be @ErikSpyro or an official contributor like @Grossley.

**Closed** 2024-01-11 21:41 UTC
Labels: bug
