### ISSUE TITLE
Can't read data.win from Swimsuit Samurai

### ISSUE THREAD

**Issue by Mirrorman95** [krzys-h/UndertaleModTool#823] opened 2022-04-05 06:55 UTC
Operating System: Windows 10
Tool Version: UndertaleModTool_NSF_v0.4.0.4

A new NSFW game demo made in GMS2 called Swimsuit Samurai was recently released on itch.io. I downloaded it from https://cyberscherzoff.itch.io/swimsuit-samurai. I tried opening its data.win file in a variety of different data.win extractors/browsers, including this one, but they all gave me various errors. This tool in particular just told me:

Load error
**Ⓧ**
An error occured while trying to load:
First list item starts inside the pointer list?!?!
at 02F1382D8 while reading object
UndertaleModLib.UndertalePointerList'1[[UndertaleModLib.
Models.UndertaleFont+Glyph, UndertaleModLib,
Version=0.4.0.4, Culture=neutral, PublicKeyToken=null]]
at 02F682D8 while reading object
UndertaleModLib.Models.UndertaleFont
while reading item 1 of 4 in a list of
UndertaleModLib.Models.UndertaleFont in chunk FONT
[OK]

**Comment by Archie-osu** [comment] 2022-04-05 07:24
Use the latest build artifact, the issue is fixed there.

**Comment by Mirrorman95** [comment] 2022-04-05 07:32
> Use the latest build artifact, the issue is fixed there.

Where can I find it?

**Comment by Miepee** [comment] 2022-04-05 09:00
You can either use UMT to update to the latest build artifact (open UndertaleModTool.exe -> File -> Settings -> Update app to latest commit), or you can go find them here: https://github.com/krzys-h/UndertaleModTool/actions/workflows/build.yml

**Comment by Mirrorman95** [comment] 2022-04-05 09:57
> You can either use UMT to update to the latest build artifact (open UndertaleModTool.exe -> File -> Settings -> Update app to latest commit), or you can go find them here: https://github.com/krzys-h/UndertaleModTool/actions/workflows/build.yml
It works now, thanks!

**Comment by Miepee** [comment] 2022-04-05 10:15
Can you close the issue if it's been resolved?

**Closed** 2022-04-05 22:00 UTC
