### ISSUE TITLE
"Origin" tab doesn't work

### ISSUE THREAD

**Issue by Looge25** [krzys-h/UndertaleModTool#789] opened 2022-03-16 23:17 UTC
When editing the origin of a sprite, the sprite's position does not change in game, but it says my changes are saved on the tool.

**Comment by Jacky720** [comment] 2022-03-16 23:20
Duplicate of #623. It may be that GameMaker no longer handles origin the same way and the tool should change available options accordingly.

**Closed** 2022-03-16 23:23 UTC
