### ISSUE TITLE
Load error (VARI, bytecode17) 

### ISSUE THREAD

**Issue by LinXP** [krzys-h/UndertaleModTool#88] opened 2018-11-20 00:57 UTC
Load error (VARI, bytecode17), example game [deathsgambit_pc_bc17.win](https://mega.nz/#F!HfxXwS5B!N_-Zfy_pgNp9KXLn3NO7RQ)  
http://i.prntscr.com/OOxEXnBwRHWONY67U9zIKQ.png
hex: http://i.prntscr.com/RlJfbkFlSCKV3UNX86O7GQ.png

**Comment by colinator27** [comment] 2018-11-20 01:03
I think I know what the issue is with it, and I think I have a fix that works, I just haven't pushed it yet.

Basically, I think that since the data file is extremely large, the Int24 in `Reference<T>.NextOccurrenceOffset` begins to write onto the first bit, or the one that determines whether the number is signed or unsigned. I believe that number should actually be a UInt24, which I implemented in my local source. But before I push, does that sound possible/right, @krzys-h?

**Comment by krzys-h** [comment] 2018-11-20 12:46
Sounds likely

**Comment by krzys-h** [comment] 2018-11-29 17:29
@colinator27 and where are the patches for this and #87? :P

**Comment by colinator27** [comment] 2018-11-29 23:18
Oh yeah, I completely forgot to *actually push* that stuff. I was working so much on the compiler. I'll do that right now.

**Comment by krzys-h** [comment] 2018-11-30 14:49
Fixed in #102

**Closed by krzys-h** 2018-11-30 14:49 UTC
Labels: data.win format, other games
