### ISSUE TITLE
High risk to data loss

### ISSUE THREAD

**Issue by Saipan0** [krzys-h/UndertaleModTool#1015] opened 2022-06-28 23:11 UTC
### Describe the bug

with the last two versions in some games I find this type of message, can you tell me how I can solve it? a thousand thanks

![img error](https://user-images.githubusercontent.com/101728572/176318927-f48acd29-e52b-4935-b47e-807b39a5ed03.png)

### Reproducing steps

I open the file and it gives an error

### Setup Details

Version tool 0.4.0.3 and 0.4.0.4.
Windows 10.

**Comment by Jacky720** [comment] 2022-06-29 00:18
Try the cutting edge pre-release.

**Comment by Miepee** [comment] 2022-06-30 18:38
>  in some games 

Would also help if you'd clarify in which games it happens.

**Comment by Saipan0** [comment] 2022-07-01 01:33
> Try the cutting edge pre-release.

ok, thanks for answering me. I tried:
- GUI-windows-latest-isBundled-true-isSingleFile-true and GUI-windows-latest-isBundled-true-isSingleFile-false
and it gives me this error when I open the file .win:

![Senza titolo](https://user-images.githubusercontent.com/101728572/176804599-90f23331-7d35-4911-bada-ae5236339fca.png)

-UndertaleModTool_NSF_v0.4.0.4 and UndertaleModTool_v0.4.0.4 they give me the error like the first post.


> > in some games
> 
> Would also help if you'd clarify in which games it happens.

I am a translator of indie games for adults. many work but others give me this error

**Comment by Saipan0** [comment] 2022-07-01 09:19
> Seems like games made with 2022.5, can you confirm that?

yes they are new games

**Comment by Miepee** [comment] 2022-07-01 10:05
Then this is a duplicate of #945 .

**Comment by Grossley** [comment] 2022-07-01 21:22
Closed as duplicate.

**Closed by Grossley** 2022-07-01 21:22 UTC
Labels: bug

**Comment by Saipan0** [comment] 2022-07-03 09:14
ok, so it's a bug?

**Comment by Miepee** [comment] 2022-07-03 15:01
It is a bug, but a known one which is why it was closed.
