### ISSUE TITLE
Save scroll position for each tab.

### ISSUE THREAD

**Issue by VladiStep** [krzys-h/UndertaleModTool#1020] opened 2022-06-30 12:46 UTC
### Which component should be improved?

UI/UX

### Describe your feature suggestion in more detail

When you switch between tabs, it doesn't keep the scroll bar position.
I'm suggesting that it should save the position when you leave the tab, and restore it when you switch back to it.

**Comment by Miepee** [comment] 2022-06-30 12:53
This is more or less a duplicate of what Nyako (and others) wanted here:
https://github.com/krzys-h/UndertaleModTool/issues/827#issuecomment-1095512889

**Comment by VladiStep** [comment] 2022-06-30 12:57
This is a part of the bigger issue.

**Closed** 2023-03-23 00:02 UTC
Labels: enhancement
