### ISSUE TITLE
Copy any asset

### ISSUE THREAD

**Issue by fireahmedgamerYT** [krzys-h/UndertaleModTool#323] opened 2020-10-14 19:48 UTC
I want a script to copy any asset like copying a room this will make it easy for who want to create a new room that looks like the other room

**Comment by fireahmedgamerYT** [comment] 2020-10-14 20:35
Im in underminers im iIfireIi

**Comment by Grossley** [comment] 2021-04-19 23:31
Duplicate of #100, closing

**Closed by Grossley** 2021-04-19 23:31 UTC
