### ISSUE TITLE
// Duplicate code entry; cannot edit here.

### ISSUE THREAD

**Issue by OhioInvadesUSA** [krzys-h/UndertaleModTool#603] opened 2021-09-28 20:02 UTC
When I try to edit GMS2.3 code in Deltarune Chapter 2, it showed me this message:
// Duplicate code entry; cannot edit here.

**Comment by Grossley** [comment] 2021-09-28 20:04
Duplicate of #583

**Closed by Grossley** 2021-09-28 20:04 UTC
