### ISSUE TITLE
Undertale yellow(gms 2.3) wont open on this

### ISSUE THREAD

**Issue by NC-devC** [krzys-h/UndertaleModTool#1564] opened 2023-12-10 08:02 UTC
### Describe the bug

![image](https://github.com/krzys-h/UndertaleModTool/assets/59499259/1962bd61-50a9-4a1b-acbf-cc9009553c8d)
I cant open data.win file from ut yellow(i tried to use experemental utmt and stable utmt) 

### Reproducing steps

1.Download undertale yellow
2.Open data.win

### Setup Details

1.Utmt: experemental and stable versions
2.Windows 10
3.Undertale yellow 1.0.0

**Comment by Dobby233Liu** [comment] 2023-12-10 08:03
Dupe of #1554

**Closed** 2023-12-13 22:14 UTC
Labels: bug
