### ISSUE TITLE
Issue with colour decompilation

### ISSUE THREAD

**Issue by constraining** [krzys-h/UndertaleModTool#172] opened 2019-05-15 12:42 UTC
EXCEPTION!
System.OverflowException: Value was either too large or too small for a UInt32.
   at System.Convert.ToUInt32(Int16 value)
   at UndertaleModLib.Decompiler.Decompiler.ExpressionConstant.ToString(DecompileContext context) in C:\Users\krzys\Documents\Visual Studio 2017\Projects\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 233
   at UndertaleModLib.Decompiler.Decompiler.ExpressionCast.ToString(DecompileContext context) in C:\Users\krzys\Documents\Visual Studio 2017\Projects\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 290
   at UndertaleModLib.Decompiler.Decompiler.FunctionCall.ToString(DecompileContext context) in C:\Users\krzys\Documents\Visual Studio 2017\Projects\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 657
   at UndertaleModLib.Decompiler.Decompiler.BlockHLStatement.ToString(DecompileContext context, Boolean canSkipBrackets) in C:\Users\krzys\Documents\Visual Studio 2017\Projects\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 1265
   at UndertaleModLib.Decompiler.Decompiler.IfHLStatement.ToString(DecompileContext context) in C:\Users\krzys\Documents\Visual Studio 2017\Projects\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 1290
   at UndertaleModLib.Decompiler.Decompiler.BlockHLStatement.ToString(DecompileContext context, Boolean canSkipBrackets) in C:\Users\krzys\Documents\Visual Studio 2017\Projects\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 1265
   at UndertaleModLib.Decompiler.Decompiler.WithHLStatement.ToString(DecompileContext context) in C:\Users\krzys\Documents\Visual Studio 2017\Projects\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 1375
   at UndertaleModLib.Decompiler.Decompiler.Decompile(UndertaleCode code, DecompileContext context) in C:\Users\krzys\Documents\Visual Studio 2017\Projects\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 2215
   at UndertaleModTool.UndertaleCodeEditor.<>c__DisplayClass11_0.<DecompileCode>b__0() in C:\Users\krzys\Documents\Visual Studio 2017\Projects\UndertaleModTool\UndertaleModTool\Editors\UndertaleCodeEditor.xaml.cs:line 265

I'm not well versed in code and even worse off on visual c++, but from what i gathered this is an issue with the string that is output in place of the actual gamemaker color values (c_black, c_white, etc). I don't have the proper extensions to compile the file myself, so if someone would do this for me i'd be glad. Here's the actual code i tried to decompile:

.localvar 0 arguments
00000: push.v self.surf
00002: call.i surface_exists(argc=1)
00004: conv.v.b
00005: not.b
00006: bf 00034
00007: pushvar.v self.room_height
00009: pushi.e 2
00010: mul.i.v
00011: pushvar.v self.room_width
00013: pushi.e 2
00014: mul.i.v
00015: call.i surface_create(argc=2)
00017: pop.v.v self.surf
00019: push.v self.surf
00021: call.i surface_set_target(argc=1)
00023: popz.v
00024: pushi.e 0
00025: conv.i.v
00026: pushi.e 0
00027: conv.i.v
00028: call.i draw_clear_alpha(argc=2)
00030: popz.v
00031: call.i surface_reset_target(argc=0)
00033: popz.v
00034: push.v self.surf
00036: call.i surface_set_target(argc=1)
00038: popz.v
00039: pushi.e 66
00040: pushenv 00087
00041: push.v self.image_alpha
00043: push.v self.image_blend
00045: push.v self.image_angle
00047: push.v self.image_yscale
00049: pushi.e 2
00050: mul.i.v
00051: push.v self.image_xscale
00053: pushi.e 2
00054: mul.i.v
00055: push.v self.y
00057: pushi.e 2
00058: mul.i.v
00059: pushi.e 2
00060: sub.i.v
00061: pushi.e 4
00062: conv.i.v
00063: call.i random(argc=1)
00065: add.v.v
00066: push.v self.x
00068: pushi.e 2
00069: mul.i.v
00070: pushi.e 2
00071: sub.i.v
00072: pushi.e 4
00073: conv.i.v
00074: call.i random(argc=1)
00076: add.v.v
00077: push.v self.image_index
00079: push.v self.sprite_index
00081: call.i draw_sprite_ext(argc=9)
00083: popz.v
00084: call.i instance_destroy(argc=0)
00086: popz.v
00087: popenv 00041
00088: pushi.e 70
00089: pushenv 00093
00090: call.i scrDrawBloodToSurface(argc=0)
00092: popz.v
00093: popenv 00090
00094: pushi.e 65
00095: pushenv 00099
00096: call.i scrDrawBloodToSurface(argc=0)
00098: popz.v
00099: popenv 00096
00100: pushi.e 68
00101: pushenv 00105
00102: call.i scrDrawBloodToSurface(argc=0)
00104: popz.v
00105: popenv 00102
00106: pushi.e 69
00107: pushenv 00151
00108: push.v self.image_alpha
00110: push.v self.image_blend
00112: push.v self.image_angle
00114: push.v self.image_yscale
00116: pushi.e 2
00117: mul.i.v
00118: push.v self.image_xscale
00120: pushi.e 2
00121: mul.i.v
00122: push.v self.y
00124: pushi.e 2
00125: mul.i.v
00126: pushi.e 2
00127: sub.i.v
00128: pushi.e 4
00129: conv.i.v
00130: call.i random(argc=1)
00132: add.v.v
00133: push.v self.x
00135: pushi.e 2
00136: mul.i.v
00137: pushi.e 2
00138: sub.i.v
00139: pushi.e 4
00140: conv.i.v
00141: call.i random(argc=1)
00143: add.v.v
00144: pushi.e 0
00145: conv.i.v
00146: pushi.e 13
00147: conv.i.v
00148: call.i draw_sprite_ext(argc=9)
00150: popz.v
00151: popenv 00108
00152: pushi.e 5
00153: pushenv 00193
00154: push.v self.speed
00156: push.d 0.1
00159: cmp.d.v LTE
00160: bf 00193
00161: push.v self.image_alpha
00163: push.v self.image_blend
00165: push.v self.image_angle
00167: push.v self.image_yscale
00169: pushi.e 2
00170: mul.i.v
00171: push.v self.image_xscale
00173: pushi.e 2
00174: mul.i.v
00175: push.v self.y
00177: pushi.e 2
00178: mul.i.v
00179: push.v self.x
00181: pushi.e 2
00182: mul.i.v
00183: push.v self.image_index
00185: push.v self.sprite_index
00187: call.i draw_sprite_ext(argc=9)
00189: popz.v
00190: call.i instance_destroy(argc=0)
00192: popz.v
00193: popenv 00154
00194: pushi.e 1
00195: pushenv 00247
00196: push.v self.speed
00198: pushi.e 0
00199: cmp.i.v EQ
00200: bf 00247
00201: pushi.e 1
00202: conv.i.v
00203: pushi.e -1
00204: conv.i.v
00205: pushi.e -1
00206: conv.i.v
00207: pushi.e -1
00208: conv.i.v
00209: pushi.e -1
00210: conv.i.v
00211: push.v self.image_angle
00213: push.v self.image_yscale
00215: pushi.e 2
00216: mul.i.v
00217: push.v self.image_xscale
00219: pushi.e 2
00220: mul.i.v
00221: push.v self.y
00223: pushi.e 2
00224: mul.i.v
00225: push.v self.x
00227: pushi.e 2
00228: mul.i.v
00229: push.v self.height
00231: push.v self.width
00233: push.v self.top
00235: push.v self.left
00237: push.v self.image_index
00239: push.v self.sprite_index
00241: call.i draw_sprite_general(argc=16)
00243: popz.v
00244: call.i instance_destroy(argc=0)
00246: popz.v
00247: popenv 00196
00248: pushi.e 7
00249: pushenv 00289
00250: push.v self.speed
00252: push.d 0.1
00255: cmp.d.v LTE
00256: bf 00289
00257: push.v self.image_alpha
00259: push.v self.image_blend
00261: push.v self.image_angle
00263: push.v self.image_yscale
00265: pushi.e 2
00266: mul.i.v
00267: push.v self.image_xscale
00269: pushi.e 2
00270: mul.i.v
00271: push.v self.y
00273: pushi.e 2
00274: mul.i.v
00275: push.v self.x
00277: pushi.e 2
00278: mul.i.v
00279: push.v self.image_index
00281: push.v self.sprite_index
00283: call.i draw_sprite_ext(argc=9)
00285: popz.v
00286: call.i instance_destroy(argc=0)
00288: popz.v
00289: popenv 00250
00290: call.i surface_reset_target(argc=0)
00292: popz.v

**Comment by Kneesnap** [comment] 2019-05-15 13:26
What commit do you have checked out?

**Comment by constraining** [comment] 2019-05-15 14:31
If by commits you mean releases, then 0.2.0 and 0.1.25. From looking at the commits, 0.2.0 appears to be the latest one.

**Comment by constraining** [comment] 2019-05-15 14:33
Also forgot to mention explicitly, the lines mentioned in the error texts are abscent from the actual decompiled assember code, so if you just copy-paste what i have given here, it should work fine.

**Comment by Kneesnap** [comment] 2019-05-18 00:55
I mean like, make sure you're using the latest version.

**Comment by Kneesnap** [comment] 2019-05-20 04:46
Also, what game + script is this?

**Comment by Kneesnap** [comment] 2019-05-25 22:29
Hrmm. I can't really look into the issue fully without being able to reproduce it.

**Comment by Kneesnap** [comment] 2019-06-04 17:07
This issue may be fixed, but I cannot test it since I do not know what script this issue pertains to. I will close it for now, if it is not fixed, it can be re-opened.

**Closed by Kneesnap** 2019-06-04 17:07 UTC
