### ISSUE TITLE
Opening big .win files.

### ISSUE THREAD

**Issue by SileNTViP** [krzys-h/UndertaleModTool#786] opened 2022-03-12 22:23 UTC
Hi.
When i try to open data.win (3.313.250.304 bytes) error: System.OverflowException: "Array dimensions exceeded supported range." in file BufferBinaryReader.cs buffer = new byte[Length];

**Comment by Archie-osu** [comment] 2022-03-13 07:17
Hi, what game is the data.win from?

**Comment by SileNTViP** [comment] 2022-03-13 12:11
> Hi, what game is the data.win from?

Secret Care Cafe 0.7.11 public :D 18+

**Comment by Archie-osu** [comment] 2022-03-13 12:35
Oh it's this game again, oh dear.

**Comment by SileNTViP** [comment] 2022-03-13 13:21
> Oh it's this game again, oh dear.

Need to change fonts and translate strings on other language.

**Comment by Miepee** [comment] 2022-03-13 13:51
Duplicate of #520 ?

**Closed** 2022-05-18 19:25 UTC
