### ISSUE TITLE
Overflow error on games using the extenstion GameMakerServer

### ISSUE THREAD

**Issue by KadeDev** [krzys-h/UndertaleModTool#289] opened 2020-05-14 00:08 UTC
Not a big issue, but I've found the decompiler goes into an exception when decompiling a script called XGms_ve_getBestWayToSend.

A sample data.win is attached.
[data.zip](https://github.com/krzys-h/UndertaleModTool/files/4625314/data.zip)

**Comment by KadeDev** [comment] 2020-05-14 00:08
Complete exception:
```
XGms_ve_getBestWayToSend. Exception: System.OverflowException: Value was either too large or too small for a Decimal.
   at System.Decimal..ctor(Double value)
   at System.Decimal.op_Explicit(Double value)
   at UndertaleModLib.Decompiler.Decompiler.ExpressionConstant.ToString(DecompileContext context) in C:\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 392
   at UndertaleModLib.Decompiler.Decompiler.ExpressionCompare.ToString(DecompileContext context) in C:\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 697
   at UndertaleModLib.Decompiler.Decompiler.ExpressionTwoSymbol.ToString(DecompileContext context) in C:\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 622
   at UndertaleModLib.Decompiler.Decompiler.AssignmentStatement.ToString(DecompileContext context) in C:\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 910
   at UndertaleModLib.Decompiler.Decompiler.BlockHLStatement.ToString(DecompileContext context, Boolean canSkipBrackets, Boolean forceSkipBrackets) in C:\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 1739
   at UndertaleModLib.Decompiler.Decompiler.IfHLStatement.ToString(DecompileContext context) in C:\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 1905
   at UndertaleModLib.Decompiler.Decompiler.BlockHLStatement.ToString(DecompileContext context, Boolean canSkipBrackets, Boolean forceSkipBrackets) in C:\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 1739
   at UndertaleModLib.Decompiler.Decompiler.IfHLStatement.ToString(DecompileContext context) in C:\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 1894
   at UndertaleModLib.Decompiler.Decompiler.Decompile(UndertaleCode code, DecompileContext context) in C:\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 2634
```

**Comment by KadeDev** [comment] 2020-05-14 00:11
(Not sure if this is related to #251, it might be.)

**Comment by Grossley** [comment] 2020-05-14 00:22
This is a duplicate of #211

**Comment by Grossley** [comment] 2020-05-14 01:02
The code in question is "gml_Script_XGms_ve_getBestWayToSend" and this error is caused due to the values of "00043: push.d -1E+38" and "00050: push.d 1E+38" in the assembly.

**Closed** 2021-05-03 23:30 UTC
