### ISSUE TITLE
Theres only the client one on macOS

### ISSUE THREAD

**Issue by deltabeanz** [krzys-h/UndertaleModTool#1262] opened 2023-04-01 19:47 UTC
Can you make the GUI one on macOS theres only the client one for macOS and I have no idea how to get that one working

**Comment by Jacky720** [comment] 2023-04-01 21:59
1. CLI stands for Command Line Interface, not client. You have to run it through the command line, but I will admit it's much harder.
2. We can't do that without reworking the entire UI to not be based on WPF; hence, this is a duplicate of #460 (and we might as well make a UI for another tool entirely; [DogScepter](https://github.com/colinator27/DogScepter) has a lot less legacy code to deal with).
3. Have you tried running the Windows GUI version through [Wine](https://www.winehq.org/)?

**Closed** 2023-05-04 18:18 UTC
Labels: enhancement
