### ISSUE TITLE
Unable to cast object of type 'Reference`1[UndertaleModLib.Models.UndertaleVariable]' to type 'UndertaleModLib.Models.UndertaleInstruction'.

### ISSUE THREAD

**Issue by tatzio** [krzys-h/UndertaleModTool#1078] opened 2022-08-29 05:16 UTC
### Describe the bug

When I attempt to open up the data.win file for the game [ZERO Sievert](https://store.steampowered.com/app/1782120/ZERO_Sievert/), I get the following error:

```
Unable to cast object of type 'Reference`1[UndertaleModLib.Models.UndertaleVariable]' to type 'UndertaleModLib.Models.UndertaleInstruction'.
at 029F2EA4 while reading object UndertaleModLib.Models.UndertaleVariable in chunk VARI
```

### Reproducing steps

1. Open ZERO Sievert `data.win` file in the tool.
2. You now see the above error message.

### Setup Details

1. 0.4.0.4 and latest bleeding edge build
2. Windows 10 64-bit
3. [ZERO Sievert](https://store.steampowered.com/app/1782120/ZERO_Sievert/)

**Comment by stutwoby** [comment] 2022-10-11 12:37
It looks like the current code has issues loading chunks for `VARI`, `TMLN `and `FUNC `.

I've managed to work around this by excluding their chunks for the unserialize method in "UndertaleChunkTypes". Rest of the load works fine.

I don't understand a lot of what's going on so I'll continue to read the research provided in the github but any pointers from someone more experienced would really help.

`var listOfExcludedChunks = new[] { "VARI", "TMLN", "FUNC" };
                if (!listOfExcludedChunks.Contains(name))
                {
                    chunk.UnserializeChunk(reader);
                }`

**Comment by HIHA-HIHA** [comment] 2022-10-19 17:30
I found that the error occurs in the Parse Reference Chain() method in the file UndertaleCode.cs on line 322 in the GetUndertaleObjectAtAddress() method, because the value {(null) is returned}. I think that's the problem, but I'm not sure.

obj {
    NextOccurrenceOffset = 60
    Target = null
    Type = Normal
}

**Comment by Nicholas-Ingram** [comment] 2022-11-21 15:01
Is there any plans for a release fixing this issue? The current Bleeding Edge release can't decompile Zero Sievert's files and seems to be the same error messages.

**Comment by colinator27** [comment] 2022-12-04 04:18
Should be fixed by https://github.com/krzys-h/UndertaleModTool/commit/c89786050a508a9e4416609da58735a742a5625c. Reopen this issue if the problem is still there, though.

**Closed by colinator27** 2022-12-04 04:18 UTC
Labels: bug
