### ISSUE TITLE
New Lines in Shaders

### ISSUE THREAD

**Issue by pnick0509** [krzys-h/UndertaleModTool#751] opened 2022-02-17 00:58 UTC
When a shader is being edited, you can see it is comprised of several lines. However, once a line is deleted, a new line cannot be created.

**Comment by Grossley** [comment] 2022-02-17 01:18
This is a text editor issue.

**Comment by pnick0509** [comment] 2022-02-18 16:40
> This is a text editor issue.

I am using the built in editor. Is this a problem on my end or with the tool itself?

**Comment by Grossley** [comment] 2022-02-18 20:18
> I am using the built in editor. Is this a problem on my end or with the tool itself?

The latter.

**Comment by pnick0509** [comment] 2022-03-10 04:09
Is there a work around or a fix for this?

**Comment by NyakoFox** [comment] 2022-03-10 04:12
is it possible for you to write a shader in a code editor then copy it in?

**Comment by pnick0509** [comment] 2022-03-10 04:16
It only seems to paste the first line.

**Comment by Grossley** [comment] 2022-03-10 08:38
Editing the actual text of the shader would not be effective for games past GMS1, as those games shaders rely on pre-compiled shader files. 

Also, this issue is a duplicate of #462. Closing.

**Closed by Grossley** 2022-03-10 08:38 UTC
