### ISSUE TITLE
Attempting to compile a certain line of code causes the program to crash immediately

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#389] opened 2021-03-15 03:37 UTC
Attempting to compile ``if global.flag[a][{}}`` causes the program to crash, as a result of an error in the compilation process.

**Comment by colinator27** [comment] 2021-05-12 00:28
This is fixed now, I think this is a duplicate of a similar issue

**Closed by colinator27** 2021-05-12 00:28 UTC
