### ISSUE TITLE
Three scripts fail to decompile in HANCHO demo

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#228] opened 2019-09-13 17:29 UTC
The following failed to decompile in the "HANCHO" demo which can be gotten [here.](https://store.steampowered.com/app/1118630)

gml_Object_obj_teambuilding_profession_Draw_0
gml_Object_window_teambuilding_new_Create_0
gml_Script_get_damage

[An error list here.](https://github.com/krzys-h/UndertaleModTool/files/3611144/error_list.txt)

**Comment by Miepee** [comment] 2022-06-12 15:46
`gml_Object_window_teambuilding_new_Create_0` compiles correctly now, `gml_Object_obj_teambuilding_profession_Draw_0`  and  `gml_Script_get_damage` are a duplicate of #452 .

**Closed** 2022-06-12 15:48 UTC
