### ISSUE TITLE
Last commit ("Truncate exception output...") disables stack trace printing in any case.

### ISSUE THREAD

**Issue by VladiStep** [krzys-h/UndertaleModTool#645] opened 2021-10-16 19:42 UTC
Commit "[Truncate exception output in general.](https://github.com/krzys-h/UndertaleModTool/commit/13ec0d7d22009e47757aafb30fa2d89401adc168)" causes `RunScriptNow()` to print **only message** of **any** `Exception`.

For example - if we throw an `InvalidOperationException` after calling `EnsureDataLoaded()` with loaded data, it will print only "_Operation is not valid due to the current state of object_" without stack trace of it.

**Comment by VladiStep** [comment] 2021-10-16 19:44
Also, I don't understand why some of scripts throws an `Exception` with message like "_Please load data.win first!_", if there is already exists `ScriptError()` function.

**Comment by Grossley** [comment] 2021-10-16 21:07
This is invalid due to the behavior described being intended, and no bug is at issue. It was explained to me that the issue occurs if this code is ran:

```
DoLongErrorMessages(false);
EnsureDataLoaded();
throw new InvalidOperationException();
```

But it can be toggled like this

```
DoLongErrorMessages(false);
EnsureDataLoaded();
DoLongErrorMessages(true);
throw new InvalidOperationException();
```

and so it does not disable stack trace printing in all cases. This is intended behavior. There may be other valid issues regarding stack trace printing or exception handling, but you should make a separate issue for those issues, and make it explicitly clear what the problem is. 

Marked as invalid and closing.

**Closed by Grossley** 2021-10-16 21:07 UTC
Labels: invalid
