### ISSUE TITLE
Attempting to recompile a section decompiled code causes "Bad variable: local.alarm"

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#406] opened 2021-04-04 05:52 UTC
```
var o, dx, dy, bv, bt, bc;
o = argument0
bv = (o.alarm[2] / 30)
```

**Comment by BenjaminUrquhart** [comment] 2021-04-04 05:53
Duplicate of #344

**Closed** 2021-04-04 05:54 UTC
