### ISSUE TITLE
I want to edit the full code in Undertale Mod Tool.

### ISSUE THREAD

**Issue by Animelici804** [krzys-h/UndertaleModTool#148] opened 2019-02-24 17:55 UTC
That would be **cool for people** that know **Game Maker Language**. I know you may say that decompilation system is bad, but I think you can **make it better** and **add code edit system**. We **would fully mod** the game, and even we could **make our own stories**! I know that's kinda like editing the game in Game Maker Studio but... **you will need to select one of two choices**.

1. You should add an option to turn the game into Game Maker Project, but not trolls please, that's bad. (you %100 won't select this)
2. Add a code editing system. (Well, maybe you won't select that... who knows?)

**Comment by Mc-muffin** [comment] 2019-02-24 20:25
The gamemaker export button is a troll because of gamemker's policy of not decompiling, however there is a work in progress high level code editor being developed by Colinator.

And thecnically you can fully mod the game right now, it's just that bigger mods are kinda tedious to do.

**Comment by Animelici804** [comment] 2019-02-25 09:13
I tried to edit the code but it didn't work. I think krzys-h should do it.

**Comment by Mc-muffin** [comment] 2019-02-26 14:08
Yeah, it currently doesn't work because it is a work in progress, as I said Colinator is working on it (check issue #34 a dupe of this one) so you'll have to wait untill he finishes.

**Comment by krzys-h** [comment] 2019-03-01 17:36
Duplicate of #43. And like @Mc-muffin said, full GMS decompile won't happen because doing that is illegal and breaks all copyright laws possible and @colinator27 was actually working on a compiler that would let you edit high-level code.

**Closed by krzys-h** 2019-03-01 17:36 UTC
