### ISSUE TITLE
StoneShard (New objects in room leads to game not booting)

### ISSUE THREAD

**Issue by CROUZi** [krzys-h/UndertaleModTool#269] opened 2020-02-24 21:37 UTC
(Game. Ver. 0.5.7.18)

Everything else seems to be working just fine, but adding new game objects into a Room will cause the game to crash on start-up. Editing existing objects or moving them around works.

No error-code or anything. Just CTD.

**Comment by Grossley** [comment] 2020-04-04 17:51
This is probably a duplicate of #260 .

**Comment by Grossley** [comment] 2020-04-04 17:53
This is a duplicate of #260 and should be closed.

**Closed** 2020-04-04 18:41 UTC
