### ISSUE TITLE
ExportAllRoomsToPng script doesn't export anything and errors out

### ISSUE THREAD

**Issue by TrashBandatcoot** [krzys-h/UndertaleModTool#1163] opened 2023-02-02 19:55 UTC
### Describe the bug

Trying to use the ExportAllRoomsToPng script just makes UndertaleModTool spit out a huge window with an error log.

![image](https://user-images.githubusercontent.com/49070403/216436093-ff0e0705-beeb-4334-a983-6d55f6f0709b.png)

### Reproducing steps

1. Go to Scripts > Resource Unpackers > ExportAllRoomsToPng.csx.
2. That's it. The script errors out and outputs a single 0 byte image.

### Setup Details

1. v0.5.0.0
2. Windows 10 (64-bit)
3. Pizza Tower, though I've tried other games built with GMS 2.3 (including one released all the way back on May 15th) and they don't work either.

**Comment by VladiStep** [comment] 2023-02-02 20:08
Duplicate - https://github.com/krzys-h/UndertaleModTool/issues/1137

**Comment by VladiStep** [comment] 2023-02-02 20:57
And the issue is fixed now.
You can either wait until 0.5.0.1 or "update to the latest commit" (you can do that in the settings).

**Closed** 2024-01-11 21:43 UTC
Labels: bug
