### ISSUE TITLE
error during loading the data

### ISSUE THREAD

**Issue by donsoyer** [krzys-h/UndertaleModTool#749] opened 2022-02-16 12:50 UTC
![MWSnap 2022-02-16, 13_48_32](https://user-images.githubusercontent.com/96090807/154267997-b22e71e0-d791-4c2c-913b-03e55df4cc55.png)

**Comment by Jacky720** [comment] 2022-02-16 12:51
Duplicate of #722

**Closed** 2022-02-16 21:56 UTC
