### ISSUE TITLE
Sugary Spire doesn't load

### ISSUE THREAD

**Issue by Blucher555** [krzys-h/UndertaleModTool#915] opened 2022-05-14 17:03 UTC
### Describe the bug

I'm trying to load Sugary Spire's (https://sugary-spire.itch.io/sugary-spire-demo) data.win on the latest commit of utmt (at the time of me publishing this issue) and it just gives me this error:
![image](https://user-images.githubusercontent.com/94925731/168441511-6eda1fec-249e-4945-b1be-33affa8b3865.png)

### Reproducing steps

1. Open the data.win
2. Profit

### Setup Details

1. I compiled from source, the commit is the latest one at the time of writing this (commit befaae88d2a416b750ab10515e81405a9b3abee7)
2. Windows 11
3. GameMaker Studio 2 (the latest runtime, i'm pretty sure)

**Comment by Miepee** [comment] 2022-05-23 12:52
Duplicate of #825

**Closed** 2022-06-12 15:25 UTC
Labels: bug
