### ISSUE TITLE
0.4.0.0-pre1 breaks Wine support

### ISSUE THREAD

**Issue by 20kdc** [krzys-h/UndertaleModTool#471] opened 2021-06-18 20:39 UTC
Tests done on Wine 6.7 on Ubuntu 20.04.2 LTS.

Using Wine with 0.3.5.8 works fine for loading and extraction of code in game.unx of Linux Undertale (latest version at time of writing).

Using Wine with 0.4.0.0-pre1 fails to load the same file with varying errors.
![image](https://user-images.githubusercontent.com/22304167/122613621-0fd46800-d07d-11eb-82b1-897ed890e65b.png)
![image](https://user-images.githubusercontent.com/22304167/122613685-2bd80980-d07d-11eb-96ac-b5032ab93ebb.png)

My diagnosis is that switching to .NET 5 has worsened compatibility because the GUI is still WPF-based (so no native Linux version) and Wine doesn't work with .NET 5 properly (because it's a New Microsoft Thing and Microsoft always breaks those on Wine)

Recommendations:
+ Change UI framework to anything not WPF
+ Go back to an earlier .NET Framework version (as early as possible is best, but 4.6.1 works)
+ Point people to the version that does actually work

**Comment by Grossley** [comment] 2021-06-18 20:41
Wine is not officially supported by UndertaleModTool, it is officially Windows only. Use Wine at your own risk.

**Comment by Grossley** [comment] 2021-06-18 20:42
Your recommendations will be

**Comment by Grossley** [comment] 2021-06-18 20:44
> Change UI framework to anything not WPF

This is possible, but there is no expected timeline for this. 

> Go back to an earlier .NET Framework version (as early as possible is best, but 4.6.1 works)

This is very unlikely as the tool has already been reworked for NET 5.0

> Point people to the version that does actually work

Yes, you should use the version(s) that actually work.

**Comment by Grossley** [comment] 2021-06-18 20:51
> Wine is not officially supported by UndertaleModTool, it is officially Windows only. Use Wine at your own risk.

We'll only really support Linux once UI isn't tied to windows. Closing.

**Closed by Grossley** 2021-06-18 20:51 UTC

**Comment by Grossley** [comment] 2021-06-18 20:54
> Using Wine with 0.3.5.8 works fine for loading and extraction of code in game.unx of Linux Undertale (latest version at time of writing).

If using 0.3.5.8 works you should use that for the time being until such time until UndertaleModTool is truly cross platform.

**Comment by leo60228** [comment] 2021-09-19 19:17
I can't reproduce this with the final release of 0.4.0.0, for what it's worth. It even fixes the rendering glitches older versions had.
